# Refer to https://github.com/softprops/action-gh-release

on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    #tags:
     # - 'v*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/Trimmomatic-*.zip
